name: sotaui
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.3

  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.1.0

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.15

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.6

  # https://pub.dev/packages/lottie
  lottie: ^1.3.0

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.1

  # https://pub.dev/packages/animate_do
  animate_do: ^3.0.2

  # https://pub.dev/packages/flutter_form_builder
  flutter_form_builder: ^7.7.0

  # https://pub.dev/packages/form_builder_validators
  form_builder_validators: ^8.4.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.7

  # https://pub.dev/packages/share_plus
  share_plus: ^6.3.0

  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.1.1

  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^2.3.4

  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.2.0

  # https://pub.dev/packages/permission_handler
  permission_handler: ^10.2.0

  # https://pub.dev/packages/syncfusion_flutter_barcodes
  syncfusion_flutter_barcodes: ^20.3.59

  # https://pub.dev/packages/sliding_up_panel
  sliding_up_panel: ^2.0.0+1

  # https://pub.dev/packages/dio
  dio: ^4.0.6

  # https://pub.dev/packages/provider
  provider: ^6.0.4

  # https://pub.dev/packages/page_transition
  page_transition: ^2.0.9

  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.11

  # https://pub.dev/packages/majascan
  majascan: ^0.5.0

  # https://pub.dev/packages/window_manager
  window_manager: ^0.2.7

  # https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^4.2.2

  # https://pub.dev/packages/encrypt
  encrypt: ^5.0.1

  # https://pub.dev/packages/file_picker
  file_picker: ^5.2.3

  # https://pub.dev/packages/image_picker
  image_picker: ^0.8.6

  # https://pub.dev/packages/table_calendar
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - assets/images/
    - assets/images/png/
    - assets/lottie/
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
